version: '3'
services:

  patika-db:
    image: postgres
    container_name: patika-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: patika-user
      POSTGRES_PASSWORD: patika-password
      POSTGRES_DB: postgres
    networks:
      - patikaNetwork


    #TODO REDIS

  patika-bootcamp-api:
    build: ./patika-bootcamp
    container_name: patika-bootcamp-api
    depends_on:
      - patika-db
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patika-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=patika-user
      - SPRING_DATASOURCE_PASSWORD=patika-password
    networks:
      - patikaNetwork

  payment-api:
    build: ./payment-api
    container_name: payment-api
    ports:
      - '8070:8080'
    networks:
      - patikaNetwork

networks:
  patikaNetwork:
    driver: "bridge"